'use client';

import React, { useState, Suspense } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import Image from 'next/image';

function ProgressReportContent() {
  const router = useRouter();
  const searchParams = useSearchParams();
  
  // Get form data from URL params
  const educatorFirstName = searchParams?.get('educatorFirstName') || '';
  const educatorLastName = searchParams?.get('educatorLastName') || '';
  const studentFirstName = searchParams?.get('studentFirstName') || '';
  const studentLastName = searchParams?.get('studentLastName') || '';
  const date = searchParams?.get('date') || '';
  const room = searchParams?.get('room') || '';
  
  const [progressAreas, setProgressAreas] = useState('');
  const [achievements, setAchievements] = useState('');
  const [nextSteps, setNextSteps] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedReport, setGeneratedReport] = useState('');

  const handleGenerateReport = async () => {
    if (!progressAreas.trim()) {
      alert('Please enter the progress areas.');
      return;
    }
    
    setIsGenerating(true);
    
    try {
      // Import AI service dynamically to avoid SSR issues
      const { aiService } = await import('@/utils/aiService');
      
      const aiResponse = await aiService.generateProgressReport(
        `${educatorFirstName} ${educatorLastName}`,
        `${studentFirstName} ${studentLastName}`,
        room,
        date,
        progressAreas,
        achievements,
        nextSteps
      );
      
      const report = `**Progress Report**

**Date:** ${date}
**Educator:** ${educatorFirstName} ${educatorLastName}
**Student:** ${studentFirstName} ${studentLastName}
**Room:** ${room}

**Emotional Development:**
${aiResponse.emotional || 'Assessment not available'}

**Physical Development:**
${aiResponse.physical || 'Assessment not available'}

**Social Development:**
${aiResponse.social || 'Assessment not available'}

**Cognitive Development:**
${aiResponse.cognitive || 'Assessment not available'}

**Language Development:**
${aiResponse.language || 'Assessment not available'}

**What's Next:**
${aiResponse.whatsNext || 'Continue supporting the child\'s growth and development.'}

**Educator's Comment:**
${aiResponse.educatorComment || 'Professional assessment completed.'}

*Report generated by Smart Story Studio AI*`;
      
      setGeneratedReport(report);
    } catch (error) {
      console.error('AI generation error:', error);
      alert('Error generating AI report. Please try again.');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleBack = () => {
    router.push('/');
  };

  const formattedDate = new Date(date).toLocaleDateString('en-GB', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit'
  });

  return (
    <div className="page-background min-h-screen">
      <div className="container mx-auto px-4 py-8">
        <div className="max-w-4xl mx-auto">
          {/* Header */}
          <div className="flex justify-between items-center mb-8">
            <button 
              onClick={handleBack}
              className="text-xl font-semibold text-blue-600 flex items-center bg-white bg-opacity-80 px-3 py-2 rounded-lg shadow-sm"
            >
              ← Back
            </button>
            <div className="text-center">
              <div className="w-20 h-20 mx-auto mb-2 bg-white rounded-2xl shadow-lg flex items-center justify-center p-1">
                <Image
                  src="/ss-logo.png"
                  alt="Smart Story Studio Logo"
                  width={60}
                  height={60}
                  className="rounded-xl"
                />
              </div>
              <h1 className="text-2xl font-black text-black">Progress Report</h1>
            </div>
            <button 
              onClick={() => router.push('/')}
              className="text-lg font-semibold text-white flex items-center bg-blue-600 px-3 py-2 rounded-lg shadow-sm"
            >
              🏠 Home
            </button>
          </div>

          {/* Report Info */}
          <div className="bg-white rounded-lg p-6 mb-6">
            <div className="grid grid-cols-2 gap-4 text-lg text-black">
              <div><strong>Date:</strong> {formattedDate}</div>
              <div><strong>Educator:</strong> {educatorFirstName} {educatorLastName}</div>
              <div><strong>Student:</strong> {studentFirstName} {studentLastName}</div>
              <div><strong>Room:</strong> {room}</div>
            </div>
          </div>

          {/* Form */}
          <div className="bg-white rounded-lg p-6 mb-6">
            <div className="space-y-6">
              <div>
                <label className="block text-xl font-semibold text-black mb-2">
                  Progress Areas <span className="text-red-500">*</span>
                </label>
                <textarea
                  value={progressAreas}
                  onChange={(e) => setProgressAreas(e.target.value)}
                  placeholder="Describe the child&apos;s progress in various areas..."
                  className="w-full p-4 border border-gray-300 rounded-lg text-lg min-h-32 resize-none text-black"
                  style={{ caretColor: 'black' }}
                />
              </div>

              <div>
                <label className="block text-xl font-semibold text-black mb-2">
                  Achievements
                </label>
                <textarea
                  value={achievements}
                  onChange={(e) => setAchievements(e.target.value)}
                  placeholder="What achievements has the child made?"
                  className="w-full p-4 border border-gray-300 rounded-lg text-lg min-h-24 resize-none text-black"
                  style={{ caretColor: 'black' }}
                />
              </div>

              <div>
                <label className="block text-xl font-semibold text-black mb-2">
                  Next Steps
                </label>
                <textarea
                  value={nextSteps}
                  onChange={(e) => setNextSteps(e.target.value)}
                  placeholder="What are the next steps for development?"
                  className="w-full p-4 border border-gray-300 rounded-lg text-lg min-h-24 resize-none text-black"
                  style={{ caretColor: 'black' }}
                />
              </div>
            </div>
          </div>

          {/* Generate Button */}
          <button
            onClick={handleGenerateReport}
            disabled={isGenerating || !progressAreas.trim()}
            className="w-full p-4 text-2xl font-bold text-white rounded-lg transition-all duration-200 mb-6"
            style={{
              backgroundColor: progressAreas.trim() ? '#AACABB' : 'rgba(128, 128, 128, 0.5)',
              cursor: progressAreas.trim() ? 'pointer' : 'not-allowed'
            }}
          >
            {isGenerating ? 'Generating Report...' : 'Generate AI Report'}
          </button>

          {/* Export Buttons */}
          <div className="flex gap-4 mb-6">
            <button
              onClick={() => {
                // Simulate email functionality
                alert('Email functionality would be implemented here');
              }}
              className="flex-1 p-4 text-xl font-bold text-white bg-green-600 rounded-lg transition-all duration-200"
            >
              Send via Email
            </button>
            <button
              onClick={() => {
                // Simulate preview functionality
                alert('Preview functionality would be implemented here');
              }}
              className="flex-1 p-4 text-xl font-bold text-white bg-orange-500 rounded-lg transition-all duration-200"
            >
              Preview
            </button>
          </div>

          {/* Generated Report */}
          {generatedReport && (
            <div className="bg-white rounded-lg p-6">
              <h2 className="text-2xl font-bold text-black mb-4">Generated Report</h2>
              <div className="bg-gray-50 rounded-lg p-4 whitespace-pre-wrap text-lg">
                {generatedReport}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

export default function ProgressReportPage() {
  return (
    <Suspense fallback={<div className="page-background min-h-screen flex items-center justify-center">
      <div className="text-2xl font-bold text-black">Loading...</div>
    </div>}>
      <ProgressReportContent />
    </Suspense>
  );
} 