'use client';

import React, { useState, Suspense } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import Image from 'next/image';

function DailyReportContent() {
  const router = useRouter();
  const searchParams = useSearchParams();
  
  // Get form data from URL params
  const educatorFirstName = searchParams?.get('educatorFirstName') || '';
  const educatorLastName = searchParams?.get('educatorLastName') || '';
  const date = searchParams?.get('date') || '';
  const room = searchParams?.get('room') || '';
  
  const [dailyActivities, setDailyActivities] = useState('');
  const [highlights, setHighlights] = useState('');
  const [notes, setNotes] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedReport, setGeneratedReport] = useState('');

  const handleGenerateReport = async () => {
    if (!dailyActivities.trim()) {
      alert('Please enter the daily activities.');
      return;
    }
    
    setIsGenerating(true);
    
    // Simulate AI report generation
    setTimeout(() => {
      const report = `**Daily Report**

**Date:** ${date}
**Educator:** ${educatorFirstName} ${educatorLastName}
**Room:** ${room}

**Daily Activities:**
${dailyActivities}

**Highlights:**
${highlights || 'A productive day with engaging activities.'}

**Notes:**
${notes || 'All children participated well in today&apos;s activities.'}

*Report generated by Smart Story Studio AI*`;
      
      setGeneratedReport(report);
      setIsGenerating(false);
    }, 3000);
  };

  const handleBack = () => {
    router.push('/');
  };

  const formattedDate = new Date(date).toLocaleDateString('en-GB', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit'
  });

  return (
    <div className="page-background min-h-screen">
      <div className="container mx-auto px-4 py-8">
        <div className="max-w-4xl mx-auto">
          {/* Header */}
          <div className="flex justify-between items-center mb-8">
            <button 
              onClick={handleBack}
              className="text-xl font-semibold text-blue-600 flex items-center bg-white bg-opacity-80 px-3 py-2 rounded-lg shadow-sm"
            >
              ← Back
            </button>
            <div className="text-center">
              <div className="w-20 h-20 mx-auto mb-2 bg-white rounded-2xl shadow-lg flex items-center justify-center p-1">
                <Image
                  src="/ss-logo.png"
                  alt="Smart Story Studio Logo"
                  width={60}
                  height={60}
                  className="rounded-xl"
                />
              </div>
              <h1 className="text-2xl font-black text-black">Daily Report</h1>
            </div>
            <button 
              onClick={() => router.push('/')}
              className="text-lg font-semibold text-white flex items-center bg-blue-600 px-3 py-2 rounded-lg shadow-sm"
            >
              🏠 Home
            </button>
          </div>

          {/* Report Info */}
          <div className="bg-white rounded-lg p-6 mb-6">
            <div className="grid grid-cols-2 gap-4 text-lg text-black">
              <div><strong>Date:</strong> {formattedDate}</div>
              <div><strong>Educator:</strong> {educatorFirstName} {educatorLastName}</div>
              <div><strong>Room:</strong> {room}</div>
              <div><strong>Report Type:</strong> Room-level report</div>
            </div>
          </div>

          {/* Form */}
          <div className="bg-white rounded-lg p-6 mb-6">
            <div className="space-y-6">
              <div>
                <label className="block text-xl font-semibold text-black mb-2">
                  Daily Activities <span className="text-red-500">*</span>
                </label>
                <textarea
                  value={dailyActivities}
                  onChange={(e) => setDailyActivities(e.target.value)}
                  placeholder="Describe today&apos;s activities and experiences..."
                  className="w-full p-4 border border-gray-300 rounded-lg text-lg min-h-32 resize-none text-black"
                  style={{ caretColor: 'black' }}
                />
              </div>

              <div>
                <label className="block text-xl font-semibold text-black mb-2">
                  Highlights
                </label>
                <textarea
                  value={highlights}
                  onChange={(e) => setHighlights(e.target.value)}
                  placeholder="What were the highlights of the day?"
                  className="w-full p-4 border border-gray-300 rounded-lg text-lg min-h-24 resize-none text-black"
                  style={{ caretColor: 'black' }}
                />
              </div>

              <div>
                <label className="block text-xl font-semibold text-black mb-2">
                  Notes
                </label>
                <textarea
                  value={notes}
                  onChange={(e) => setNotes(e.target.value)}
                  placeholder="Any additional notes or observations..."
                  className="w-full p-4 border border-gray-300 rounded-lg text-lg min-h-24 resize-none text-black"
                  style={{ caretColor: 'black' }}
                />
              </div>
            </div>
          </div>

          {/* Generate Button */}
          <button
            onClick={handleGenerateReport}
            disabled={isGenerating || !dailyActivities.trim()}
            className="w-full p-4 text-2xl font-bold text-white rounded-lg transition-all duration-200 mb-6"
            style={{
              backgroundColor: dailyActivities.trim() ? '#AACABB' : 'rgba(128, 128, 128, 0.5)',
              cursor: dailyActivities.trim() ? 'pointer' : 'not-allowed'
            }}
          >
            {isGenerating ? 'Generating Report...' : 'Generate AI Report'}
          </button>

          {/* Export Buttons */}
          <div className="flex gap-4 mb-6">
            <button
              onClick={() => {
                // Simulate email functionality
                alert('Email functionality would be implemented here');
              }}
              className="flex-1 p-4 text-xl font-bold text-white bg-green-600 rounded-lg transition-all duration-200"
            >
              Send via Email
            </button>
            <button
              onClick={() => {
                // Simulate preview functionality
                alert('Preview functionality would be implemented here');
              }}
              className="flex-1 p-4 text-xl font-bold text-white bg-orange-500 rounded-lg transition-all duration-200"
            >
              Preview
            </button>
          </div>

          {/* Generated Report */}
          {generatedReport && (
            <div className="bg-white rounded-lg p-6">
              <h2 className="text-2xl font-bold text-black mb-4">Generated Report</h2>
              <div className="bg-gray-50 rounded-lg p-4 whitespace-pre-wrap text-lg">
                {generatedReport}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

export default function DailyReportPage() {
  return (
    <Suspense fallback={<div className="page-background min-h-screen flex items-center justify-center">
      <div className="text-2xl font-bold text-black">Loading...</div>
    </div>}>
      <DailyReportContent />
    </Suspense>
  );
} 