'use client';

import React, { useState, Suspense } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import Image from 'next/image';

function ObservationReportContent() {
  const router = useRouter();
  const searchParams = useSearchParams();
  
  // Get form data from URL params
  const educatorFirstName = searchParams?.get('educatorFirstName') || '';
  const educatorLastName = searchParams?.get('educatorLastName') || '';
  const studentFirstName = searchParams?.get('studentFirstName') || '';
  const studentLastName = searchParams?.get('studentLastName') || '';
  const date = searchParams?.get('date') || '';
  const room = searchParams?.get('room') || '';
  
  const [activityDescription, setActivityDescription] = useState('');
  const [selectedFocusAreas, setSelectedFocusAreas] = useState<string[]>([]);
  const [whatsNext, setWhatsNext] = useState('');
  const [educatorComment, setEducatorComment] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedReport, setGeneratedReport] = useState('');

  const focusAreas = ["Wellbeing", "Identity", "Learning", "Communication", "Community"];

  const handleFocusAreaToggle = (area: string) => {
    if (selectedFocusAreas.includes(area)) {
      setSelectedFocusAreas(selectedFocusAreas.filter(a => a !== area));
    } else {
      setSelectedFocusAreas([...selectedFocusAreas, area]);
    }
  };

  const handleGenerateReport = async () => {
    if (!activityDescription.trim()) {
      alert('Please enter the activity description.');
      return;
    }
    
    if (selectedFocusAreas.length === 0) {
      alert('Please select at least one focus area.');
      return;
    }
    
    setIsGenerating(true);
    
    try {
      // Import AI service dynamically to avoid SSR issues
      const { aiService } = await import('@/utils/aiService');
      
      const aiResponse = await aiService.generateObservationReport(
        `${educatorFirstName} ${educatorLastName}`,
        `${studentFirstName} ${studentLastName}`,
        room,
        date,
        activityDescription,
        selectedFocusAreas
      );
      
      const report = `**Observation Report**

**Date:** ${date}
**Educator:** ${educatorFirstName} ${educatorLastName}
**Student:** ${studentFirstName} ${studentLastName}
**Room:** ${room}
**Focus Areas:** ${selectedFocusAreas.join(', ')}

**Activity Description:**
${aiResponse.activity}

**What's Next:**
${aiResponse.whatsNext}

**Educator's Comment:**
${aiResponse.comment}

*Report generated by Smart Story Studio AI*`;
      
      setGeneratedReport(report);
    } catch (error) {
      console.error('AI generation error:', error);
      alert('Error generating AI report. Please try again.');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleBack = () => {
    router.push('/');
  };

  const formattedDate = new Date(date).toLocaleDateString('en-GB', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit'
  });

  return (
    <div className="page-background min-h-screen">
      <div className="container mx-auto px-4 py-8">
        <div className="max-w-4xl mx-auto">
          {/* Header */}
          <div className="flex justify-between items-center mb-8">
            <button 
              onClick={handleBack}
              className="text-xl font-semibold text-blue-600 flex items-center bg-white bg-opacity-80 px-3 py-2 rounded-lg shadow-sm"
            >
              ← Back
            </button>
            <div className="text-center">
              <div className="w-16 h-16 mx-auto mb-2 bg-white rounded-xl shadow-lg flex items-center justify-center">
                <Image
                  src="/ss-logo.png"
                  alt="Smart Story Studio Logo"
                  width={64}
                  height={64}
                  className="rounded-lg"
                />
              </div>
              <h1 className="text-2xl font-black text-black">Observation Report</h1>
            </div>
            <button 
              onClick={() => router.push('/')}
              className="text-lg font-semibold text-white flex items-center bg-blue-600 px-3 py-2 rounded-lg shadow-sm"
            >
              🏠 Home
            </button>
          </div>

          {/* Report Info */}
          <div className="bg-white rounded-lg p-6 mb-6">
            <div className="grid grid-cols-2 gap-4 text-lg text-black">
              <div><strong>Date:</strong> {formattedDate}</div>
              <div><strong>Educator:</strong> {educatorFirstName} {educatorLastName}</div>
              <div><strong>Student:</strong> {studentFirstName} {studentLastName}</div>
              <div><strong>Room:</strong> {room}</div>
            </div>
          </div>

          {/* Form */}
          <div className="bg-white rounded-lg p-6 mb-6">
            <div className="space-y-6">
              <div>
                <label className="block text-xl font-semibold text-black mb-2">
                  Activity Description <span className="text-red-500">*</span>
                </label>
                <textarea
                  value={activityDescription}
                  onChange={(e) => setActivityDescription(e.target.value)}
                  placeholder="Describe the activity and your observations..."
                  className="w-full p-4 border border-gray-300 rounded-lg text-lg min-h-32 resize-none text-black"
                  style={{ caretColor: 'black' }}
                />
              </div>

              <div>
                <label className="block text-xl font-semibold text-black mb-2">
                  Focus Areas <span className="text-red-500">*</span>
                </label>
                <div className="grid grid-cols-3 gap-3">
                  {focusAreas.map((area) => (
                    <button
                      key={area}
                      onClick={() => handleFocusAreaToggle(area)}
                      className={`p-3 rounded-lg border-2 transition-all duration-200 ${
                        selectedFocusAreas.includes(area)
                          ? 'bg-blue-600 text-white border-blue-600'
                          : 'bg-white text-black border-gray-300 hover:border-blue-400'
                      }`}
                    >
                      {area}
                    </button>
                  ))}
                </div>
              </div>

              <div>
                <label className="block text-xl font-semibold text-black mb-2">
                  What&apos;s Next
                </label>
                <textarea
                  value={whatsNext}
                  onChange={(e) => setWhatsNext(e.target.value)}
                  placeholder="What are the next steps based on this observation?"
                  className="w-full p-4 border border-gray-300 rounded-lg text-lg min-h-24 resize-none text-black"
                  style={{ caretColor: 'black' }}
                />
              </div>

              <div>
                <label className="block text-xl font-semibold text-black mb-2">
                  Educator&apos;s Comment
                </label>
                <textarea
                  value={educatorComment}
                  onChange={(e) => setEducatorComment(e.target.value)}
                  placeholder="Any additional comments or observations?"
                  className="w-full p-4 border border-gray-300 rounded-lg text-lg min-h-24 resize-none text-black"
                  style={{ caretColor: 'black' }}
                />
              </div>
            </div>
          </div>

          {/* Generate Button */}
          <button
            onClick={handleGenerateReport}
            disabled={isGenerating || !activityDescription.trim() || selectedFocusAreas.length === 0}
            className="w-full p-4 text-2xl font-bold text-white rounded-lg transition-all duration-200 mb-6"
            style={{
              backgroundColor: (activityDescription.trim() && selectedFocusAreas.length > 0) ? '#AACABB' : 'rgba(128, 128, 128, 0.5)',
              cursor: (activityDescription.trim() && selectedFocusAreas.length > 0) ? 'pointer' : 'not-allowed'
            }}
          >
            {isGenerating ? 'Generating Report...' : 'Generate AI Report'}
          </button>

          {/* Export Buttons */}
          <div className="flex gap-4 mb-6">
            <button
              onClick={() => {
                // Navigate to preview with report data
                const params = new URLSearchParams({
                  title: 'Observation Report',
                  educatorName: `${educatorFirstName} ${educatorLastName}`,
                  studentName: `${studentFirstName} ${studentLastName}`,
                  room: room,
                  date: date,
                  content: generatedReport,
                  reportType: 'Observation'
                });
                router.push(`/preview?${params.toString()}`);
              }}
              className="flex-1 p-4 text-xl font-bold text-white bg-orange-500 rounded-lg transition-all duration-200"
            >
              Preview
            </button>
            <button
              onClick={async () => {
                try {
                  const { pdfService } = await import('@/utils/pdfService');
                  await pdfService.downloadPDF({
                    title: 'Observation Report',
                    educatorName: `${educatorFirstName} ${educatorLastName}`,
                    studentName: `${studentFirstName} ${studentLastName}`,
                    room: room,
                    date: date,
                    content: generatedReport,
                    reportType: 'Observation'
                  });
                } catch (error) {
                  console.error('PDF download error:', error);
                  alert('Failed to download PDF. Please try again.');
                }
              }}
              className="flex-1 p-4 text-xl font-bold text-white bg-blue-600 rounded-lg transition-all duration-200"
            >
              Download PDF
            </button>
          </div>

          {/* Generated Report */}
          {generatedReport && (
            <div className="bg-white rounded-lg p-6">
              <h2 className="text-2xl font-bold text-black mb-4">Generated Report</h2>
              <div className="bg-gray-50 rounded-lg p-4 whitespace-pre-wrap text-lg">
                {generatedReport}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

export default function ObservationReportPage() {
  return (
    <Suspense fallback={<div className="page-background min-h-screen flex items-center justify-center">
      <div className="text-2xl font-bold text-black">Loading...</div>
    </div>}>
      <ObservationReportContent />
    </Suspense>
  );
} 